import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MiniKitProvider from "@/components/minikit-provider";
import NextAuthProvider from "@/components/next-auth-provider";
import { ErudaProvider } from "@/components/Eruda";
import AuthGuard from "@/components/AuthGuard"; // ✅ Importamos AuthGuard

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    };

    export default function RootLayout({
    children,
    }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <NextAuthProvider>
            <ErudaProvider>
                <MiniKitProvider>
                <AuthGuard>{children}</AuthGuard> {/* 🔥 Protege la app */}
                </MiniKitProvider>
            </ErudaProvider>
            </NextAuthProvider>
        </body>
        </html>
    );
}
